version: "3.1"
services:
  web:
    container_name: app_github
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    ports:
      - "4567:4567"
    volumes:
      - .:/app
    links:
      - db
    depends_on:
      - db
      - redis

  db:
    container_name: app_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: rubydb

  redis:
    container_name: app_redis
    image: redis:alpine
    ports:
      - "6379:6379"