version: "3.1"
services:
  web:
    container_name: app_github
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - ./code:/usr/src/app/
    ports:
      - "4567:4567"
    links:
      - db

  db:
    container_name: app_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  redis:
    container_name: app_redis
    image: redis:alpine
    ports:
      - "6379:6379"