version: "3.1"
services:
  web:
    container_name: app_git
    build: .
    command: bash -c "while [ true ]; do sleep 10; done"
    volumes:
      - ./code:/usr/src/app/
    ports:
      - "4567:4567"
    links:
      - db

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

